Algoritmo "Lista 1 - ex2_Marco"



Var
   d,t,v: real
   nome :caractere


Inicio
      escreval("Digite o nome do piloto")
      leia(nome)
      escreval("Digite a ditancia em KM")
      leia(d)
      escreval("Digite o tempo levado para percorrear a ditancia em horas")
      leia(t)
      
      v <- d/t
      
      escreval("A velocidade média do ", nome, " foi ", v, " km/h.")



Fimalgoritmo