Algoritmo "LISTA 2 - EX1_MARCO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2026
Var
// Seção de Declarações das variáveis 
n: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("DIGITE UM N°")
   leia(n)
   
   SE (n >= 1) E (n <= 9) ENTAO
        escreval("O valor está na faixa permitida")
   SENAO
        escreval("O valor está fora da faixa permitida")
   FIMSE




Fimalgoritmo